#!/bin/sh
set -e
if [ "$1" = "configure" -a -x /usr/bin/update-menus ]; then update-menus ; fi

if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/gwhere -a -d /usr/share/doc/gwhere ]; then
    ln -sf ../share/doc/gwhere /usr/doc/gwhere
  fi
fi